# Generated by Django 6.0.7 on 2026-07-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_useraddress'),
        ('menu', '0003_category_alter_fooditem_category'),
        ('orders', '0003_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed Amount', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum total times this coupon can be used', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('one_time_per_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='menu.category')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='menu.fooditem')),
                ('excluded_products', models.ManyToManyField(blank=True, related_name='excluded_coupons', to='menu.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='accounts.user')),
            ],
        ),
    ]
