# Generated by Django 6.0.7 on 2026-07-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('menu', '0003_category_alter_fooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popular_items', to='menu.category'),
        ),
    ]
